### ISSUE TITLE
node.selectNodes(xpath) fails in IE 10

### ISSUE THREAD

**Issue by tyler-ham** [hpehl/totoe#5]
XML parsing fails in IE 10 at name.pehl.totoe.xml.client.internal.NodeImpl > selectNodesImpl() > node.selectNodes(xpath).

sarissa.js checks for IE9 and provides fixes and initializations required for IE 9+. IE 10 needs (at least some of) these fixes, but is not currently recognized by Sarissa's check for IE9 (Sarissa._SARISSA_IS_IE9).

There is a bug report in the Sarissa project covering a similar issue, and the fix is the same.
http://sourceforge.net/p/sarissa/bugs/62/

**Comment by hpehl** [comment]
Should be fixed with https://github.com/hpehl/totoe/pull/6
