### ISSUE TITLE
Question about license terms for totoe

### ISSUE THREAD

**Issue by johnkarnes** [hpehl/totoe#7]
Thanks for a great tool.  My team is using this in a little applet with wizards to help build XSLT.
I have a question about the license terms for using totoe.  In GWT it identified it as an Apache 2.0, but here in GitHub I see no mention of terms.

Kind regards,
John Karnes

**Comment by hpehl** [comment]
Added Apache 2.0 license

**Comment by johnkarnes** [comment]
Harald – Thank You!
John
